# Generated by Django 3.1.2 on 2020-10-20 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='latest',
            field=models.BooleanField(default=False),
        ),
    ]
