# Generated by Django 3.1.2 on 2020-10-20 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browse', '0002_video_latest'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='type_vid',
            field=models.BooleanField(default=True),
        ),
    ]
