# Generated by Django 3.1.2 on 2020-10-23 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('browse', '0003_video_type_vid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='type_vid',
            new_name='is_vid',
        ),
    ]
